### PR TITLE
Add engines to package.json

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by feross** [comment]
How did you determine to use this version?

**Comment by MichaelDeBoey** [comment]
@feross I took the same engines as `standard` (the only dependency) has at this moment:

https://github.com/standard/standard/blob/6bb55a1dbb042231ae255bad5bb60d9044ca6bc6/package.json#L36-L38

**Comment by LinusU** [comment]
This package is for the web platform, and thus doesn't really support any version of Node.js at all?

**Comment by MichaelDeBoey** [comment]
@LinusU Specifying the minimum node version is useful to know which minimum version is required to serve this package

**Comment by LinusU** [comment]
> [...] minimum version is required to serve this package

But is there anything preventing someone to serve this package from e.g. Node.js 4.0?

**Comment by MichaelDeBoey** [comment]
Like I said: `standard` (which is a dependency) requires Node@8.10

**Comment by LinusU** [comment]
`standard` is just a dev-dependency, and shouldn't affect the required version to use the package. It's only required to run the tests in the repository, but isn't included if you install `clipboard-copy` from npm :)

**Comment by MichaelDeBoey** [comment]
But you still need Node@8.10 when running/building `clipboard-copy` locally

**Comment by LinusU** [comment]
Well, there is neither a concept of "running" nor "building" clipboard-copy. The only thing that requires Node.js 8.10 is running the linting.

That being said, I still think that `engines` is for indicating which version you need to _consume_ to library, not to work on it locally 🤔 

If we were to merge this, would it then be a breaking change to bump that version? And in that case, do we have to release a new major version when we upgrade the internal linting in the future?

Also, and maybe most importantly, what would we gain from adding the engines field?

**Comment by feross** [comment]
This PR doesn't make sense for a browser library.

**Pull request closed without merging**
