### PR TITLE
Add TypeScript type definitions

### PR DESCRIPTION
**Pull request by LinusU**
Hey @feross,

Not sure if you like adding this to your packages or not, so feel free to reject. Also, if you need a helping hand maintaining this package I'd be happy to help out.

Cheers 👋

### CODE REVIEW

**Comment by ahstro** [comment]
Bumping this, because it looks like a super quick and easy merge and it'd be quite handy to have 😊

**Comment by feross** [comment]
I'm afraid to merge this since I'm not a Typescript user (yet?) and I don't think I would do a good job keeping it up-to-date.

@LinusU What are the pros-cons of adding this here vs. somewhere else?

**Comment by LinusU** [comment]
The pros of adding it here is that it doesn't require TypeScript users to fetch the typings from somewhere else (e.g. `npm install -D @types/clipboard-copy`) or manually adding typings in `typings.d.ts`.

The con would be that it needs to be kept up to date when we make changes (although that is true if it were hosted elsewhere though).

I'm using this in a project using TypeScript currently, and I have to add this to my `typings.d.ts` file. The less stuff I can have in there the happier I am since I need to maintain that for every project.

I'd be happy to hop on as a maintainer and make sure that the typings are always up to date!

**Comment by feross** [comment]
@LinusU Okay, that seems fair! Added you as a contributor.

**Comment by feross** [comment]
Published as 1.2.1

**Comment by LinusU** [comment]
Awesome 🙌

**Pull request merged**
